services:
  moriarty:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - ENV_VAR=example_value
    command: bash run.sh
